#!/bin/bash
# =============================================================================
# Daily Report Script
# Generate daily activity summary from logs
# =============================================================================

source "$(dirname "$0")/common.sh"

print_header "📊 Daily Activity Report"

TODAY=$(date +%Y-%m-%d)
REPORT_FILE="$REPORTS_DIR/daily_report_$TODAY.html"

setup_dirs

print_step "📅 Generating report for $TODAY"

# Count today's alerts
LOG_FILE="$LOGS_DIR/streamware.log"
if [ -f "$LOG_FILE" ]; then
    TOTAL_ALERTS=$(grep -c "\[$TODAY\].*\[ALERT\]" "$LOG_FILE" 2>/dev/null || echo 0)
    TOTAL_CHECKS=$(grep -c "\[$TODAY\]" "$LOG_FILE" 2>/dev/null || echo 0)
else
    TOTAL_ALERTS=0
    TOTAL_CHECKS=0
fi

# Count today's reports
REPORT_COUNT=$(ls -1 "$REPORTS_DIR"/*$TODAY* 2>/dev/null | wc -l || echo 0)

# Generate HTML report
cat > "$REPORT_FILE" << EOF
<!DOCTYPE html>
<html>
<head>
    <title>Daily Security Report - $TODAY</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-900 text-white p-8">
    <div class="max-w-4xl mx-auto">
        <h1 class="text-3xl font-bold mb-4">📊 Daily Security Report</h1>
        <p class="text-gray-400 mb-8">Generated: $(date '+%Y-%m-%d %H:%M:%S')</p>
        
        <div class="grid grid-cols-3 gap-4 mb-8">
            <div class="bg-gray-800 p-6 rounded-lg text-center">
                <div class="text-4xl font-bold text-yellow-400">$TOTAL_CHECKS</div>
                <div class="text-gray-400 mt-2">Total Checks</div>
            </div>
            <div class="bg-gray-800 p-6 rounded-lg text-center">
                <div class="text-4xl font-bold text-red-400">$TOTAL_ALERTS</div>
                <div class="text-gray-400 mt-2">Alerts</div>
            </div>
            <div class="bg-gray-800 p-6 rounded-lg text-center">
                <div class="text-4xl font-bold text-blue-400">$REPORT_COUNT</div>
                <div class="text-gray-400 mt-2">Reports</div>
            </div>
        </div>
        
        <h2 class="text-xl font-bold mb-4">📋 Alert Log</h2>
        <div class="bg-gray-800 rounded-lg p-4 font-mono text-sm max-h-96 overflow-y-auto">
EOF

# Add log entries
if [ -f "$LOG_FILE" ]; then
    grep "\[$TODAY\].*\[ALERT\]" "$LOG_FILE" 2>/dev/null | while read line; do
        echo "            <div class=\"py-1 border-b border-gray-700\">$line</div>" >> "$REPORT_FILE"
    done
fi

cat >> "$REPORT_FILE" << EOF
        </div>
        
        <h2 class="text-xl font-bold mt-8 mb-4">📁 Generated Reports</h2>
        <div class="bg-gray-800 rounded-lg p-4">
            <ul class="space-y-2">
EOF

# List today's reports
ls -1 "$REPORTS_DIR"/*$TODAY*.html 2>/dev/null | while read file; do
    filename=$(basename "$file")
    echo "                <li><a href=\"$filename\" class=\"text-blue-400 hover:underline\">📄 $filename</a></li>" >> "$REPORT_FILE"
done

cat >> "$REPORT_FILE" << EOF
            </ul>
        </div>
        
        <footer class="mt-8 pt-4 border-t border-gray-700 text-gray-500 text-sm">
            <p>Generated by Streamware • $(date '+%Y-%m-%d %H:%M:%S')</p>
        </footer>
    </div>
</body>
</html>
EOF

print_success "Daily report generated: $REPORT_FILE"

print_step "📊 Summary"

echo "Date: $TODAY"
echo "Total checks: $TOTAL_CHECKS"
echo "Alerts: $TOTAL_ALERTS"
echo "Reports generated: $REPORT_COUNT"
echo ""

# Send daily summary
if [ "$TOTAL_ALERTS" -gt 0 ]; then
    send_alert "📊 Daily Summary ($TODAY): $TOTAL_ALERTS alerts from $TOTAL_CHECKS checks"
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💡 Schedule daily with cron:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Run daily at midnight"
echo "0 0 * * * cd $(pwd) && ./14_daily_report.sh"
echo ""
